server:
  servlet:
    context-path: /api

app:
  alpha-vantage:
    url: https://www.alphavantage.co/query
    key: Demo

logging:
  file:
    name: logs/volatilator.log
    max-size: 3MB
    max-history: 2

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "* ,prometheus"
